export const environment = {
    ttApiKey: 'urES86sMdjoeMbhSLu9EK3ksu0Jjpb91',
    localhostApi: 'http://localhost:8081/api/',
    ttApiUrl: 'https://api.tomtom.com/',
    activeDriverMarker: 'src/assets/active-driver-marker.png',
    inactiveDriverMarker: 'src/assets/inactive-driver-marker.png',
    startLatitude: 45.253446,
    startLongitude: 19.8304217,
    startZoom: 13,
    unregisteredUserHomePageBgImage: "src/assets/unregistered-home-bg-img.png",
    registerSideImg: "src/assets/register-side-img.png",
    taxiIcon: "src/assets/taxi.png",
    socketUrl: 'http://localhost:8081/api/socket',
    taxiMarker: 'src/assets/icons8-taxi-96.png',
}; 